version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
image:
  - Visual Studio 2015
configuration: Release
platform:
  - x86
  - x64

init:
- ps: |-
    if ($Env:PLATFORM -eq "x64") {
        $Env:QT_ROOT = "C:\Qt\5.11\msvc2015_64"
    } else {
        $Env:QT_ROOT = "C:\Qt\5.11\msvc2015"
    }

    $Env:Path += ";${Env:QT_ROOT}\bin;C:\Program Files\7-Zip"

    function Invoke-CmdScript {
      param(
        [String] $scriptName
      )
      $cmdLine = """$scriptName"" $args & set"
      & $Env:SystemRoot\system32\cmd.exe /c $cmdLine |
      select-string '^([^=]*)=(.*)$' | foreach-object {
        $varName = $_.Matches[0].Groups[1].Value
        $varValue = $_.Matches[0].Groups[2].Value
        set-item Env:$varName $varValue
      }
    }

    Invoke-CmdScript "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${Env:PLATFORM}

before_build:
- ps: |-
    & qmake

build_script:
- ps: |-
    & cmd /c 'nmake release 2>&1'

after_build:
- ps: |-
    & nmake clean

    Set-Location -Path release
    windeployqt --release --no-opengl-sw --no-compiler-runtime ./
    Set-Location -Path ..

    New-Item -ItemType Directory -Force -Path dist | Out-Null

    $DeployName = ""

    if ($Env:APPVEYOR_REPO_TAG -eq false) {
      Write-Output "Skipping deployment for this branch..."
      Exit-AppveyorBuild
    } else {
      $DeployName = "${Env:APPVEYOR_PROJECT_NAME}-${Env:APPVEYOR_REPO_BRANCH}-win-${Env:PLATFORM}"
    }

    Write-Output "Deploy name " + $DeployName

    & 7z a -mx=9 "dist\${DeployName}.zip" release

artifacts:
- path: dist/*
deploy:
- provider: GitHub
  auth_token:
    secure: OSN3hS1Nu0oSZDsDQYPb2zOh81VqQkXe6ovY0lc5McI9ePncR7Gio0TVZYgeupJb
  draft: true
  on:
    APPVEYOR_REPO_TAG: true